parameters:
#    videl_markdown.example.class: Videl\MarkdownBundle\Example

services:
#    videl_markdown.example:
#        class: %videl_markdown.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    videl_markdown.twig.markdown_extension:
        class: Videl\MarkdownBundle\Twig\MarkdownExtension
        tags:
            - { name: twig.extension }